project:
  type: website
  output-dir: docs

website:
  title: "Zainab"
  favicon: files/favicon.ico      # optional: add a small favicon in files/
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: Bio.qmd
        text: Bio
      - href: Conference.qmd
        text: Research
      - href: Teaching.qmd
        text: Teaching
      - href: Project.qmd
        text: Projects
      - href: gallery.qmd
        text: Gallery
      - href: files/CV_ZNB.pdf
        text: CV
        target: _blank
    search: true                   # enable site search (built-in)

format:
  html:
    theme: litera
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap
    css: Styles.css                # custom CSS (placed in project root)
    toc: false

execute:
  freeze: auto


